const logs = [
  { id: 1, timestamp: "2023-10-27 14:32:01 UTC", user: { name: "John Smith", role: "Fleet Manager", initial: "JS", type: "User" }, action: "APPROVE_L1", entity: "BK-78291", entityType: "Booking", description: "Approved level 1 vehicle requisition for Department B.", ip: "10.12.4.18", source: "FleetDesk Console" },
  { id: 2, timestamp: "2023-10-27 13:45:19 UTC", user: { name: "System Auto", role: "Telemetry Daemon", initial: "", type: "System Agent" }, action: "MAINT_FLAG", entity: "VEH-A112", entityType: "Vehicle", description: "Automated flag: Engine oil pressure dropped below 30 PSI.", source: "Vehicle Telemetry" },
  { id: 3, timestamp: "2023-10-27 11:07:43 UTC", user: { name: "Elena Rodriguez", role: "Dispatcher", initial: "ER", type: "User" }, action: "CREATE_BOOKING", entity: "BK-78292", entityType: "Booking", description: "Created a new dispatch booking for overnight cargo movement.", ip: "10.12.4.77", source: "FleetDesk Console" },
  { id: 4, timestamp: "2023-10-27 09:21:08 UTC", user: { name: "Security Policy", role: "Auth Gateway", initial: "", type: "Security" }, action: "AUTH_FAIL", entity: "USR-998", entityType: "User", description: "Multiple invalid credentials detected. Account access was denied.", ip: "192.168.1.104", source: "Identity Gateway" },
  { id: 5, timestamp: "2023-10-26 18:02:33 UTC", user: { name: "John Smith", role: "Fleet Manager", initial: "JS", type: "User" }, action: "UPDATE_ROUTE", entity: "RT-Alpha", entityType: "Route", description: "Updated transport route to avoid scheduled terminal maintenance.", ip: "10.12.4.18", source: "FleetDesk Console" },
];
export async function getActivityLogs() { return logs; }
export function filterActivityLogs(data, filters) { return data.filter((log) => (filters.userType === "All Types" || log.user.type === filters.userType) && (filters.action === "All Actions" || log.action === filters.action) && (filters.entityType === "All Entities" || log.entityType === filters.entityType) && `${log.timestamp} ${log.user.name} ${log.action} ${log.entity} ${log.description}`.toLowerCase().includes(filters.search.toLowerCase())); }
export function exportActivityLogs() { const blob = new Blob(["Timestamp,User,Action,Entity,Description\n" + logs.map((log) => [log.timestamp, log.user.name, log.action, log.entity, `"${log.description}"`].join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "fleetdesk-activity-log.csv"; anchor.click(); URL.revokeObjectURL(url); }
